apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgclusters.radondb.com
  labels:
    vendor: radondb
spec:
  group: radondb.com
  names:
    kind: Pgcluster
    listKind: PgclusterList
    plural: pgclusters
    singular: pgcluster
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clustername: { type: string }
                ccpimage: { type: string }
                ccpimagetag: { type: string }
                database: { type: string }
                exporterport: { type: string }
                name: { type: string }
                pgbadgerport: { type: string }
                PrimaryStorage:
                  type: object
                  properties:
                    name: { type: string }
                    storageclass: { type: string }
                    accessmode: { type: string }
                    size: { type: string }
                    supplementalgroups: { type: string }
                    matchLabels: { type: string }
                    storagetype: { type: string }
                port: { type: string }
                policies: { type: string }
                ccpimageprefix: { type: string }
                pgoimageprefix: { type: string }
                disableAutofail: { type: boolean }
                pgBadger: { type: boolean }
                exporter: { type: boolean }
                WALStorage:
                  type: object
                  properties:
                    name: { type: string }
                    storageclass: { type: string }
                    accessmode: { type: string }
                    size: { type: string }
                    supplementalgroups: { type: string }
                    matchLabels: { type: string }
                    storagetype: { type: string }
                ReplicaStorage:
                  type: object
                  properties:
                    name: { type: string }
                    storageclass: { type: string }
                    accessmode: { type: string }
                    size: { type: string }
                    supplementalgroups: { type: string }
                    matchLabels: { type: string }
                    storagetype: { type: string }
                PGAdminStorage:
                  type: object
                  properties:
                    name: { type: string }
                    storageclass: { type: string }
                    accessmode: { type: string }
                    size: { type: string }
                    supplementalgroups: { type: string }
                    matchLabels: { type: string }
                    storagetype: { type: string }
                backrestResources:
                  type: object
                  properties:
                    cpu: { type: string }
                    memory: { type: string }
                limits:
                  type: object
                  properties:
                    cpu: { type: string }
                    memory: { type: string }
                resources:
                  type: object
                  properties:
                    cpu: { type: string }
                    memory: { type: string }
                backrestLimits:
                  type: object
                  properties:
                    cpu: { type: string }
                    memory: { type: string }
                exporterResources:
                  type: object
                  properties:
                    cpu: { type: string }
                    memory: { type: string }
                exporterLimits:
                  type: object
                  properties:
                    cpu: { type: string }
                    memory: { type: string }
                PgBouncer:
                  type: object
                  properties:
                    replicas: { type: integer }
                    resources:
                      type: object
                      properties:
                        cpu: { type: string }
                        memory: { type: string }
                    limits:
                      type: object
                      properties:
                        cpu: { type: string }
                        memory: { type: string }
                    size: { type: string }
                    serviceType: { type: string }
                    TLSSecret: { type: string }
                User: { type: string }
                PasswordType: { type: string }
                Database: { type: string }
                Replicas: { type: string }
                Status: { type: string }
                CustomConfig: { type: string }
                userlabels:
                  type: object
                  additionalProperties:
                    type: string
                    pgo-version: { type: string }
                    workflowid: { type: string }
                NodeAffinity: { type: object }
                PodAntiAffinity: { type: object }
                SyncReplication: { type: boolean }
                BackrestConfig:
                  type: array
                  items:
                    type: object
                    properties:
                      additionalProperties: { type: string }
                BackrestGCSBucket: { type: string }
                BackrestGCSEndpoint: { type: string }
                BackrestGCSKeyType: { type: string }
                BackrestS3Bucket: { type: string }
                BackrestS3Region: { type: string }
                BackrestS3Endpoint: { type: string }
                BackrestS3URIStyle: { type: string }
                BackrestS3VerifyTLS: { type: string }
                BackrestRepoPath: { type: string }
                BackrestStorageTypes:
                  type: array
                  items:
                    type: string
                BackrestStorage:
                  type: object
                  properties:
                    name: { type: string }
                    storageclass: { type: string }
                    accessmode: { type: string }
                    size: { type: string }
                    supplementalgroups: { type: string }
                    matchLabels: { type: string }
                    storagetype: { type: string }
                TablespaceMounts:
                  type: object
                  properties:
                    name: { type: string }
                    storageclass: { type: string }
                    accessmode: { type: string }
                    size: { type: string }
                    supplementalgroups: { type: string }
                    matchLabels: { type: string }
                    storagetype: { type: string }
                TLS:
                  type: object
                  properties:
                    caSecret: { type: string }
                    replicationTLSSecret: { type: string }
                    tlsSecret: { type: string }
                TLSOnly: { type: boolean }
                Standby: { type: boolean }
                Shutdown: { type: boolean }
                PGDataSource:
                  type: object
                  properties:
                    namespace: { type: string }
                    restoreFrom: { type: string }
                    restoreOpts: { type: string }
                Annotations:
                  type: object
                  properties:
                    annotations: { type: string }
                ServiceType: { type: string }
                Tolerations:
                  type: array
                  items:
                    type: object
                    properties:
                      key: { type: string }
                      operator: { type: string }
                      value: { type: string }
                      effect: { type: string }
                      tolerationSeconds: { type: integer }
            status:
              type: object
              properties:
                state: { type: string }
                message: { type: string }