---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgpolicies.radondb.com
  labels:
    vendor: radondb
spec:
  group: radondb.com
  names:
    kind: Pgpolicy
    listKind: PgpolicyList
    plural: pgpolicies
    singular: pgpolicy
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      validation:
        openAPIV3Schema:
          properties:
            status:
              properties:
                state: { type: string }
                message: { type: string }
