---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgreplicas.radondb.com
  labels:
    vendor: radondb
spec:
  group: radondb.com
  names:
    kind: Pgreplica
    listKind: PgreplicaList
    plural: pgreplicas
    singular: pgreplica
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            properties:
              state: { type: string }
              message: { type: string }
