---
apiVersion: qingcloud.com/v1
kind: Pgcluster
metadata:
  annotations: { current-primary: 'hippo' }
  name: hippo
  labels:
    qingcloud-pgha-scope: hippo
    deployment-name: hippo
    name: hippo
    namespace: pgo
    pg-cluster: hippo
    pgo-version: '${PGO_VERSION}'
spec:
  name: hippo
  namespace: pgo
  clustername: hippo
  ccpimage: qingcloud-postgres-ha
  ccpimagetag: '${CCP_IMAGE_TAG}'
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 5Gi
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: hippo
    size: 5Gi
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 5Gi
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  database: hippo
  exporterport: '9187'
  pgbadgerport: '10000'
  podAntiAffinity:
    default: preferred
  port: '5432'
  user: hippo
  userlabels:
    pgo-version: '${PGO_VERSION}'

---
apiVersion: qingcloud.com/v1
kind: Pgreplica
metadata:
  name: example
spec: {}
status: {}

---
apiVersion: qingcloud.com/v1
kind: Pgpolicy
metadata:
  name: example
spec: {}
status: {}

---
apiVersion: qingcloud.com/v1
kind: Pgtask
metadata:
  name: example
spec: {}
