# The values is for the namespace and the postgresql cluster name
name: hippo
namespace: pgo
password: W4tch0ut4hippo$

# Optional parameters
# cpu: 0.25
# diskSize: 5Gi
# monitoring: true
# ha: true
# imagePrefix: docker.io/radondb
# image: radondb-postgres-ha
# imageTag: debian-14.2-2.1.1
# memory: 1Gi
